;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	js2-mode-show-node
	js2r-inline-var
	))

(setq mc/cmds-to-run-once
      '(
	js2r-extract-var
	))
